#!/usr/bin/env python3
"""
Train a YOLOv8 model on your defect dataset.

EXPECTED DATASET LAYOUT (standard Ultralytics format)
-------------------------------------------------------
backend/dataset/
├── images/
│   ├── train/   <- put your training images here (.jpg/.png)
│   └── val/     <- put your validation images here
├── labels/
│   ├── train/   <- one .txt per training image, same basename
│   └── val/     <- one .txt per validation image, same basename
└── data.yaml    <- auto-generated by this script if missing

LABEL FORMAT
------------
Each labels/*.txt file uses standard YOLO format, one line per object:
    <class_id> <x_center> <y_center> <width> <height>
All coordinates normalized to [0, 1]. Example for an image with one
crack roughly centered:
    0 0.512 0.487 0.230 0.180

CLASS LIST
----------
Defaults to the 5 defect classes already used by the frontend mock data:
    0 Crack
    1 Discoloration
    2 Dent
    3 Surface Defect
    4 Shape Defect
Override with --classes if your dataset uses different labels (order
matters — it must match the class_id values in your label files).

USAGE
-----
    # put images/labels in backend/dataset/{images,labels}/{train,val}/
    python scripts/train.py --epochs 100 --batch 16 --model yolov8n.pt

    # resume / fine-tune from your previous best checkpoint
    python scripts/train.py --model storage/models/best.pt --epochs 50

After training, the script copies the best checkpoint to
storage/models/best.pt, which is what app/services/inference.py loads
automatically — no further wiring needed, just restart the API (or it
will pick it up on next inference call since the model is loaded lazily
and reloaded when the resolved weights path changes).
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent
DATASET_DIR = BACKEND_DIR / "dataset"
IMAGES_TRAIN = DATASET_DIR / "images" / "train"
IMAGES_VAL = DATASET_DIR / "images" / "val"
LABELS_TRAIN = DATASET_DIR / "labels" / "train"
LABELS_VAL = DATASET_DIR / "labels" / "val"
DATA_YAML = DATASET_DIR / "data.yaml"
MODELS_DIR = BACKEND_DIR / "storage" / "models"

DEFAULT_CLASSES = ["Crack", "Discoloration", "Dent", "Surface Defect", "Shape Defect"]


def write_data_yaml(classes: list[str]) -> None:
    content = (
        f"path: {DATASET_DIR.as_posix()}\n"
        f"train: images/train\n"
        f"val: images/val\n"
        f"\n"
        f"nc: {len(classes)}\n"
        f"names: {classes!r}\n"
    )
    DATA_YAML.write_text(content)
    print(f"[train.py] Wrote {DATA_YAML}")


def validate_dataset() -> None:
    problems = []
    for d in [IMAGES_TRAIN, IMAGES_VAL, LABELS_TRAIN, LABELS_VAL]:
        d.mkdir(parents=True, exist_ok=True)

    n_train_imgs = sum(1 for _ in IMAGES_TRAIN.glob("*") if _.suffix.lower() in
                        {".jpg", ".jpeg", ".png", ".bmp"})
    n_val_imgs = sum(1 for _ in IMAGES_VAL.glob("*") if _.suffix.lower() in
                      {".jpg", ".jpeg", ".png", ".bmp"})

    if n_train_imgs == 0:
        problems.append(
            f"No training images found in {IMAGES_TRAIN}. "
            "Add your images there (and matching labels in labels/train/)."
        )
    if n_val_imgs == 0:
        problems.append(
            f"No validation images found in {IMAGES_VAL}. "
            "Add a held-out set there (and matching labels in labels/val/)."
        )

    # spot-check that every image has a matching label file (warn only)
    missing_labels = []
    for img in list(IMAGES_TRAIN.glob("*")) + list(IMAGES_VAL.glob("*")):
        if img.suffix.lower() not in {".jpg", ".jpeg", ".png", ".bmp"}:
            continue
        label_dir = LABELS_TRAIN if img.parent == IMAGES_TRAIN else LABELS_VAL
        label_path = label_dir / (img.stem + ".txt")
        if not label_path.exists():
            missing_labels.append(str(img.relative_to(DATASET_DIR)))

    if missing_labels:
        print(
            f"[train.py] WARNING: {len(missing_labels)} image(s) have no matching "
            f"label file (treated as background/no-object). First few:\n  "
            + "\n  ".join(missing_labels[:5])
        )

    if problems:
        print("[train.py] Dataset is not ready:")
        for p in problems:
            print(f"  - {p}")
        print(
            "\nExpected layout:\n"
            "  backend/dataset/images/train/*.jpg\n"
            "  backend/dataset/images/val/*.jpg\n"
            "  backend/dataset/labels/train/*.txt\n"
            "  backend/dataset/labels/val/*.txt\n"
        )
        sys.exit(1)

    print(f"[train.py] Found {n_train_imgs} train images, {n_val_imgs} val images.")


def main():
    parser = argparse.ArgumentParser(description="Train YOLOv8 on the defect dataset")
    parser.add_argument("--model", default="yolov8n.pt",
                         help="Base model to start from, e.g. yolov8n.pt / yolov8s.pt / "
                              "yolov8m.pt, or a path to a previous best.pt to fine-tune")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--device", default=None,
                         help="cuda device, e.g. 0 or 0,1 or 'cpu'. Default: auto-detect")
    parser.add_argument("--classes", nargs="+", default=DEFAULT_CLASSES,
                         help="Class names in class_id order")
    parser.add_argument("--project", default=str(BACKEND_DIR / "runs"),
                         help="Where ultralytics writes run artifacts")
    parser.add_argument("--name", default="defect_detection")
    parser.add_argument("--patience", type=int, default=20,
                         help="Early stopping patience (epochs with no improvement)")
    parser.add_argument("--no-validate-dataset", action="store_true",
                         help="Skip the pre-flight dataset check")
    args = parser.parse_args()

    if not args.no_validate_dataset:
        validate_dataset()

    write_data_yaml(args.classes)

    try:
        from ultralytics import YOLO
    except ImportError:
        print(
            "[train.py] The 'ultralytics' package is not installed.\n"
            "Install it with: pip install ultralytics --break-system-packages"
        )
        sys.exit(1)

    print(f"[train.py] Loading base model: {args.model}")
    model = YOLO(args.model)

    train_kwargs = dict(
        data=str(DATA_YAML),
        epochs=args.epochs,
        batch=args.batch,
        imgsz=args.imgsz,
        patience=args.patience,
        project=args.project,
        name=args.name,
    )
    if args.device is not None:
        train_kwargs["device"] = args.device

    print(f"[train.py] Starting training: {train_kwargs}")
    results = model.train(**train_kwargs)

    # Locate best.pt from this run and copy it into storage/models/ so the
    # API picks it up automatically.
    run_dir = Path(results.save_dir)
    best_weights = run_dir / "weights" / "best.pt"
    if best_weights.exists():
        MODELS_DIR.mkdir(parents=True, exist_ok=True)
        dest = MODELS_DIR / "best.pt"
        shutil.copy(best_weights, dest)
        print(f"[train.py] Copied best weights to {dest}")
        print("[train.py] Restart the API (or just wait for the next request — "
              "the model reloads automatically) to start using the new weights.")
    else:
        print(f"[train.py] WARNING: could not find best.pt at {best_weights}")

    print("[train.py] Done. Full run artifacts (curves, confusion matrix, etc.) "
          f"are in: {run_dir}")


if __name__ == "__main__":
    main()
